---
deployment:
  tasks:
    - export DEPLOYPATH=/home/j2ykz030ddm5/public_html/uracarealtyph.com/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -a --exclude='.git' --exclude='.cpanel.yml' --exclude='.gitignore' --exclude='config/config.local.php' --exclude='storage/sessions/*' ./ $DEPLOYPATH
